crds:
  install: true
  keep: true
configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
    accounts.demo: login
  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:admin, *, *, *, allow
      g, admin, role:admin

      p, role:demo-app-kustomize, *, *, demo-app-kustomize/*, allow
      g, demo, role:demo-app-kustomize
      # TODO: bind real OIDC groups when SSO is configured
      # g, myorg:platform-team, role:admin
