apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-chart-pg
  namespace: demo-app-chart
spec:
  instances: 3
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: demo_chart_prod
  postgresql:
    parameters:
      max_connections: "200"
