apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nexhub-pg
  namespace: nexhub
spec:
  instances: 3
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: django_prod
  postgresql:
    parameters:
      max_connections: "200"
