apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-local-pg
  namespace: demo-app-local
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: demo_local
      owner: demo-local
  postgresql:
    parameters:
      max_connections: "50"
