apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-umbrella-pg
  namespace: demo-app-umbrella
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: demo_umbrella
      owner: demo-umbrella
  postgresql:
    parameters:
      max_connections: "50"
