apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-app-kustomize-chart-pg
  namespace: demo-app-kustomize-chart
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: demo_app_kustomize_chart
      owner: demo-app-kustomize-chart
  postgresql:
    parameters:
      max_connections: "50"
