apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-pg
  namespace: demo-app
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: demo
      owner: demo
  postgresql:
    parameters:
      max_connections: "50"
