apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ecflow-web-pg
  namespace: ecflow-web
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: django
      owner: ecflow_web
  postgresql:
    parameters:
      max_connections: "50"
