apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: expert-pg
  namespace: expert
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: django
      owner: expert
  postgresql:
    parameters:
      max_connections: "50"
